dataset: ${dataset}
experiment: ${experiment}
case: ${case}
variables: ${variables}
save_name: ${save_name}
clean_obs_dir: ${clean_obs_dir}
staging_dir: ${paths.staging_dir}
transforms:
  - _target_: inr4ssh._src.geoprocess.coords.transform_360_to_180
    _partial_: True

  - _target_: inr4ssh._src.geoprocess.subset.subset_time
    _partial_: True
    time_min: "2012-10-02"
    time_max: "2012-12-02"
    drop: True

  # - _target_: inr4ssh._src.geoprocess.subset.subset_longitude
  #   _partial_: True
  #   lon_min: -65.0
  #   lon_max: -55.0
  #   drop: True

  - _target_: inr4ssh._src.geoprocess.subset.subset_latitude
    _partial_: True
    lat_min: 33.0
    lat_max: 43.0
    drop: True
